CREATE DATABASE IF NOT EXISTS VIS;
USE VIS;

DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Mechanics;
DROP TABLE IF EXISTS Managers;

CREATE TABLE Customers (
    customerID INT AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(100),
    password VARCHAR(255)  
);

CREATE TABLE Mechanics (
    mechanicID INT AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(100),
    password VARCHAR(255)  
);

CREATE TABLE Managers (
    managerID INT AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(100),
    password VARCHAR(255)  
);
